<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

<h1  class="position-relative py-2 px-4 text-bg-secondary border border-secondary rounded-pill mt-4 mb-4">Upload</h1>

<?php if (!empty($error))echo $error; ?>

<form method="POST" enctype="multipart/form-data">
    <input type="file" name="image_file" accept="images/*">
    <input type="submit" name="upload" value="Upload">

</form>


