<?php
// session_start();
?>

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">    
    <title>Connexion</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    
    <style>
        .formulaire {
            display: grid;
            justify-content: center;
        }

        h1{
            text-align: center;
            margin-bottom: 2%;
        }

    </style>

</head>
<body>

    <h1>Connexion ✌</h1>


    <!-- Connexion -->

    <form method="POST" class="formulaire"> 
        <div class="mb-3 col">
            <label for="exampleInputEmail1" class="form-label">Email</label>
            <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="mail" placeholder="ea@gmail.com">
        </div>
        <div class="mb-3 col" >
            <label for="exampleInputPassword1" class="form-label">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword1" name="mdp" autocomplete="off">
        </div>
        <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Se rappeller de moi</label>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary" name="envoi">Connexion</button> <span>OU</span>
            <a href="?page=inscription" class="btn btn-primary" name="inscription">S'inscrire</a>
        </div>
        
    </form>

   

</body>
</html>