<h3 class="position-relative py-1 px-4 text-bg-green border border-secondary rounded-pill mt-4 mb-4">Admin Add Picture</h3>

<form method="POST">

    <div class="mb-3">
        <label for="source" class="form-label">Source</label>
        <input type="text" class="form-control" id="source" name="source" >
    </div>

    <div class="mb-3">
        <label for="title" class="form-label">Tile</label>
        <input type="text" class="form-control" id="title" name="title" >
    </div>

    <div class="mb-3">
        <label for="description" class="form-label">Description</label>
        <input type="text" class="form-control" id="description"  name="description">
    </div>

    <div class="mb-3">
        <label for="author" class="form-label">Author</label>
        <input type="text" class="form-control" id="author"  name="author">
    </div>

    <div class="mb-3">
        
        <input type="submit" class="btn btn-primary" value="Add Picture" name="submit" placeholder="Another input placeholder">
    </div>



</form>