<?php
// session_start();
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inscription</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    
    <style>
        .formulaire {
            display: grid;
            justify-content: center;
        }

        h1{
            text-align: center;
            margin-bottom: 2%;
        }

    </style>
</head>


<body>
    <h1>Inscription 😎</h1>

    <!-- INSCRIPTIONS -->

    <form method="POST" class="formulaire">

        <div class="mb-3 col">
            <label for="source" class="form-label">Nom</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Eroudini">
        </div>

        <div class="mb-3 col">
            <label for="title" class="form-label">Prenom</label>
            <input type="text" class="form-control" id="firstName" name="firstName" placeholder="ABDILLAH">
        </div>

        <div class="mb-3 col">
            <label for="description" class="form-label">Mail</label>
            <input type="text" class="form-control" id="mail" name="mail" placeholder="ea@gmail.com">
        </div>

        <div class="mb-3 col">
            <label for="author" class="form-label">Mot de passe</label>
            <input type="password" class="form-control" id="mdp" name="mdp">
        </div>

        <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">J'accepte les conditions</label>
        </div>

        <div class="mb-3">

            <input type="submit" class="btn btn-primary" value="S'inscrire" name="inscription" placeholder="Another input placeholder"> <span>OU</span>
            <a href="?page=connexion" class="btn btn-primary" name="Se connecter">Se connecter</a>
        </div>

    </form>

</body>

</html>