
<h3 class="position-relative py-1 px-4 text-bg-green border border-secondary rounded-pill mt-4 mb-4">Details</h3>

<!--  -->
<h1 class="mb-3 text-center"><?= $pic['title'] ?></h1>
<section class="row">
    <div class="col-12">
        <img src="<?= $pic['source'] ?>" alt="<?= $pic['title'] ?>" class="img-fluid">
    </div>
    <div class="col-12 mt-3">
        <p><?= $pic['description'] ?></p>
    </div>
    <div class="col-6 mt-3 fst-italic font-weight-light">
        <p><?= $pic['update_at'] ?></p>
    </div>
    <div class="col-6 mt-3 fst-italic font-weight-light">
        <p><?= $pic['author'] ?></p>
    </div>
</section>


