
<h4  class="position-relative py-2 px-4 text-bg-secondary border border-secondary rounded-pill mt-4 mb-4">Admin List</h4>

<a href="?page=adminadd" class="btn btn-primary m-1">Add Picture</a>

<table class="table table-striped-columns">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">ID</th>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Author</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <?php foreach ($pictures as $key => $pic) : ?>


        <tr>
            <td><img width="100" src=" <?= $pic['source'] ?>" alt="<?= $pic['title'] ?>"></td>
            <th><?= $pic['id'] ?></th>
            <td><?= $pic['title'] ?></td>
            <td><?= $pic['description'] ?></td>
            <td><?= $pic['author'] ?></td>
            <td>
                <a href="?page=update&id=<?= $pic['id'] ?>" class="btn btn-warning m-1">Update</a>

                <a href="javascript:deletePicture(<?= $pic['id'] ?>)" class="btn btn-danger m-1">Delete</a>
            </td>

        </tr>

    <?php endforeach ?>
</table>

<script>

    function deletePicture(id) {
    const question = window.confirm("Êtes vous sûr de vouloir supprimer" + id + " ?");
    if (question) {
      location.href = "?page=admindelete&id=" + id;
    }
  }

</script>

<!-- <script>
    function updatePicture(id){
        location.href = "?page=update&id=" + id;
    }
</script> -->


<a href="?page=adminadd" class="btn btn-primary m-1">Add Picture</a>





